### ISSUE TITLE
[AVFormatContext @ 0x149804080] Requested output format 'rtmp' is not known.

### ISSUE THREAD

**Issue by Ahua9527** [alim-zanibekov/ndi_streamer#1]
Have you not finished writing this yet? Why is [AVFormatContext @ 0x149804080] requested output format 'rtmp' not known
My ffmpeg has rtmp, and I have also tried using ffmpeg directly to convert a video file into an rtmp stream and push it to the rtmp server

**Comment by alim-zanibekov** [comment]
Hi @Ahua9527, can you try replacing `opts.output_format` with `"flv"` here and tell me if it works?

https://github.com/alim-zanibekov/ndi_streamer/blob/75b4df473974d957f787a4cb00c74e72044e9227/src/ndi_streamer.c#L84
